version: '3'
services:
  monitor:
    image: gr0vity/nanonodemonitor:latest
    restart: unless-stopped
    ports:
     - 80:80
    volumes:
     - ~:/opt
    networks:
     - nano-network
  node:
    image: nanocurrency/nano:V18.0
    restart: unless-stopped
    ports:
     - 7075:7075/udp
     - 7075:7075
     - 7076:7076
    volumes:
     - ~:/root
    networks:
     - nano-network

  netdata:
     image: gr0vity/nanonetdata:latest
     hostname:  nanoNodeMonitor# set to fqdn of host
     ports:
       - 19999:19999
     cap_add:
       - SYS_PTRACE
     security_opt:
       - apparmor:unconfined
     volumes:
       - /proc:/host/proc:ro
       - /sys:/host/sys:ro
       - /var/run/docker.sock:/var/run/docker.sock:ro
     networks:
       - nano-network
networks:
  nano-network:

